import { jsPDF } from "jspdf";

type MCQ = {
  question: string;
  options: string[];
  answer: string;
};

type Props = {
  mcqs: MCQ[];
  title: string;
  difficulty: string;
  questionCount: number | string;
  fileName: string;
};

export function downloadQuizPDF({
  mcqs,
  title,
  difficulty,
  questionCount,
  fileName,
}: Props) {
  const doc = new jsPDF();

  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();

  let y = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("StudyDif", pageWidth / 2, y, {
    align: "center",
  });

  y += 7;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(11);

  doc.text(
    "Generated by StudyDif AI",
    pageWidth / 2,
    y,
    {
      align: "center",
    }
  );

  y += 7;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);

  doc.text(
    "AI Practice Questions",
    pageWidth / 2,
    y,
    {
      align: "center",
    }
  );

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  doc.text(`Topic: ${title}`, 20, y);

  y += 7;

  doc.text(`Difficulty: ${difficulty}`, 20, y);

  y += 7;

  doc.text(`Questions: ${questionCount}`, 20, y);

  y += 5;

  doc.line(20, y, pageWidth - 20, y);

  y += 10;

  mcqs.forEach((mcq, index) => {
    const question = doc.splitTextToSize(
      `${index + 1}. ${mcq.question}`,
      170
    );

    const neededHeight =
      question.length * 7 +
      mcq.options.length * 7 +
      12;

    if (y + neededHeight > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.text(question, 20, y);

    y += question.length * 7;

    doc.setFont("helvetica", "normal");

    mcq.options.forEach((option, i) => {
      const optionText = doc.splitTextToSize(
        `${String.fromCharCode(65 + i)}. ${option}`,
        160
      );

      doc.text(optionText, 28, y);

      y += optionText.length * 7;
    });

    doc.setFont("helvetica", "bold");

    doc.text(`Answer: ${mcq.answer}`, 28, y);

    y += 10;
  });

  doc.save(fileName);
}