"use client";

import { useState } from "react";
import Link from "next/link";

import Button from "@/components/Button";
import Textarea from "@/components/Textarea";
import SectionTitle from "@/components/SectionTitle";
import MCQCard from "@/components/MCQCard";
import { jsPDF } from "jspdf";

type MCQ = {
  question: string;
  options: string[];
  answer: string;
};

export default function MCQGenerator() {
  const [studyMode, setStudyMode] = useState<"topic" | "notes">("topic");

  const [topic, setTopic] = useState("");
  const [notes, setNotes] = useState("");

  const [difficulty, setDifficulty] = useState("Medium");
  const [questionCount, setQuestionCount] = useState(10);

  const [loading, setLoading] = useState(false);

  const [mcqs, setMcqs] = useState<MCQ[]>([]);
  const [errorMessage, setErrorMessage] = useState("");

  
    function downloadPDF() {
  const doc = new jsPDF();

  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("USEME", pageWidth / 2, y, { align: "center" });

y += 7;

doc.setFontSize(11);
doc.setFont("helvetica", "italic");
doc.text("Generated by UseMe AI", pageWidth / 2, y, {
  align: "center",
});

y += 7;

doc.setFont("helvetica", "bold");
doc.setFontSize(16);
doc.text("Practice Questions", pageWidth / 2, y, {
  align: "center",
});

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  doc.text(
    `Topic: ${studyMode === "topic" ? topic : "From Notes"}`,
    20,
    y
  );

  y += 7;

  doc.text(`Difficulty: ${difficulty}`, 20, y);

  y += 7;

  doc.text(`Questions: ${questionCount}`, 20, y);

  y += 5;

  doc.line(20, y, pageWidth - 20, y);

  y += 10;

  mcqs.forEach((mcq, index) => {
    // Wrap question
    const question = doc.splitTextToSize(
      `${index + 1}. ${mcq.question}`,
      170
    );

    // Estimate required height
    const neededHeight =
      question.length * 7 +
      mcq.options.length * 7 +
      12;

    // New page if needed
    if (y + neededHeight > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.text(question, 20, y);

    y += question.length * 7;

    doc.setFont("helvetica", "normal");

    mcq.options.forEach((option, i) => {
      const optionText = doc.splitTextToSize(
        `${String.fromCharCode(65 + i)}. ${option}`,
        160
      );

      doc.text(optionText, 28, y);

      y += optionText.length * 7;
    });

    doc.setFont("helvetica", "bold");
    doc.text(`Answer: ${mcq.answer}`, 28, y);

    y += 10;
  });

  const fileName = `${
  (studyMode === "topic" ? topic : "Practice-Questions")
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .replace(/\s+/g, "-")
}-${new Date().toISOString().split("T")[0]}.pdf`;

doc.save(fileName);
}

  async function generateMCQs() {
    if (studyMode === "topic" && !topic.trim()) {
      alert("Please enter a topic.");
      return;
    }

    if (studyMode === "notes" && !notes.trim()) {
      alert("Please paste your notes.");
      return;
    }

    setLoading(true);
    setMcqs([]);

    try {
      const response = await fetch("/api/generate-mcq", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          studyMode,
          topic,
          notes,
          difficulty,
          questionCount,
        }),
      });

      const data = await response.json();

      if (!data.success) {
        setErrorMessage(data.message);
        setLoading(false);
        return;
      }

      setMcqs(data.result);

      setTimeout(() => {
        document
          .getElementById("results")
          ?.scrollIntoView({ behavior: "smooth" });
      }, 150);
    } catch (error) {
      console.error(error);
      alert("Something went wrong.");
    }

    setLoading(false);
  }

  return (
    <main className="min-h-screen bg-gray-100 p-8">

      <div className="mx-auto max-w-5xl rounded-2xl bg-white p-8 shadow-lg">

        <Link
          href="/"
          className="mb-6 inline-block rounded-lg bg-gray-200 px-4 py-2 text-black hover:bg-gray-300"
        >
          ← Back to Home
        </Link>

        <h1 className="text-4xl font-bold text-black">
          Practice Questions
        </h1>

        <p className="mt-2 text-gray-600">
          Generate exam-level MCQs using AI.
        </p>

        <div className="mt-8 flex gap-3">

          <button
            onClick={() => setStudyMode("topic")}
            className={`flex-1 rounded-xl p-3 font-semibold transition ${
              studyMode === "topic"
                ? "bg-blue-600 text-white"
                : "bg-gray-200 text-black"
            }`}
          >
            📚 Topic
          </button>

          <button
            onClick={() => setStudyMode("notes")}
            className={`flex-1 rounded-xl p-3 font-semibold transition ${
              studyMode === "notes"
                ? "bg-blue-600 text-white"
                : "bg-gray-200 text-black"
            }`}
          >
            📝 Notes
          </button>

        </div>

        {studyMode === "topic" ? (

          <div className="mt-6">

            <SectionTitle>
              Topic
            </SectionTitle>

            <input
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Example: Indian Constitution"
              className="mt-2 w-full rounded-xl border bg-white p-4 text-black"
            />

          </div>

        ) : (

          <div className="mt-6">

            <SectionTitle>
              Notes
            </SectionTitle>

            <Textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Paste your notes here..."
            />

          </div>

        )}

        <div className="mt-6">

          <SectionTitle>
            Difficulty
          </SectionTitle>

          <select
            value={difficulty}
            onChange={(e) => setDifficulty(e.target.value)}
            className="mt-2 w-full rounded-xl border bg-white p-3 text-black"
          >
            <option>Easy</option>
            <option>Medium</option>
            <option>Hard</option>
          </select>

        </div>

        <div className="mt-6">

          <SectionTitle>
            Number of Questions
          </SectionTitle>

          <select
            value={questionCount}
            onChange={(e) => setQuestionCount(Number(e.target.value))}
            className="mt-2 w-full rounded-xl border bg-white p-3 text-black"
          >
            <option value={10}>10</option>
            <option value={20}>20</option>
            <option value={50}>50</option>
          </select>

        </div>

        {errorMessage && (
  <div className="mt-6 rounded-xl border border-yellow-300 bg-yellow-50 p-5">
    <h3 className="font-semibold text-yellow-800">
      🤔 {errorMessage}
    </h3>

    <p className="mt-2 text-sm text-yellow-700">
      Check the spelling or explore a trending topic below.
    </p>

    <div className="mt-4 flex flex-wrap gap-2">
      {[
        "Artificial Intelligence",
        "World History",
        "Python",
        "Machine Learning",
        "Human Anatomy",
        "Climate Change",
      ].map((item) => (
        <button
          key={item}
          onClick={() => {
            setTopic(item);
            setErrorMessage("");
          }}
          className="rounded-full bg-white px-4 py-2 text-sm text-black shadow hover:bg-gray-100"
        >
          {item}
        </button>
      ))}
    </div>
  </div>
)}

        <Button
          onClick={generateMCQs}
          disabled={loading}
          className="mt-8 w-full py-4"
        >
          {loading
            ? "⏳ Generating Questions..."
            : "🚀 Generate Questions"}
        </Button>
                {mcqs.length > 0 && (

          <div
            id="results"
            className="mt-12 rounded-2xl border border-gray-200 bg-white shadow-lg"
          >

            <div className="rounded-t-2xl bg-blue-600 px-6 py-5 text-white">

              <h2 className="text-3xl font-bold">
                📚 Practice Questions
              </h2>

              <div className="mt-3 space-y-1 text-blue-100">

                <p>
                  <span className="font-semibold">Topic:</span>{" "}
                  {studyMode === "topic" ? topic : "From Notes"}
                </p>

                <p>
                  <span className="font-semibold">Difficulty:</span>{" "}
                  {difficulty}
                </p>

                <p>
                  <span className="font-semibold">Questions:</span>{" "}
                  {questionCount}
                </p>

              </div>

            </div>

            <div className="p-8">

              {mcqs.map((mcq, index) => (
                <MCQCard
                  key={index}
                  index={index}
                  mcq={mcq}
                />
              ))}

            </div>

          </div>

        )}

        {mcqs.length > 0 && (

          <Button
            className="mt-8 w-full bg-green-600 hover:bg-green-700"
            onClick={downloadPDF}
          >
            📄 Download / Print PDF
          </Button>

        )}

      </div>

    </main>
  );
}